export const es = {
  language: { label: 'Idioma', english: 'Inglés', turkish: 'Turco', german: 'Alemán', chinese: 'Chino', spanish: 'Español', hindi: 'Hindi' },
  navigation: { explore: 'Explorar', title: 'Explorar el sitio', close: 'Cerrar navegación', home: 'Inicio', recent: 'Notas recientes', personal: 'Nota personal', allArticles: 'Todos los artículos', categories: 'Categorías', categoriesEmpty: 'Las categorías aparecerán aquí', unavailable: 'Categorías no disponibles', primary: 'Navegación principal', mobile: 'Navegación móvil', open: 'Abrir navegación', index: 'Navegación' },
  home: { scroll: 'Desplázate para entrar', local: 'Local', recent: 'Notas recientes', viewAll: 'Ver todo', personal: 'Nota personal', currently: 'Actualmente', interested: 'Intereses', archive: 'Explorar el archivo', latestLoading: 'Cargando artículos recientes', offlineTitle: 'El archivo está desconectado', offlineMessage: 'Inicia la API para cargar los artículos publicados.', emptyTitle: 'Aún no hay artículos publicados', emptyMessage: 'Los artículos publicados aparecerán aquí.', status: 'Estado del archivo' },
  archive: { title: 'Todos los artículos', description: 'Textos sobre software, sistemas, interfaces y experimentos en curso.', notes: 'artículos', loading: 'Cargando artículos', label: 'Archivo de artículos', status: 'Estado del archivo', offlineTitle: 'El archivo está desconectado', emptyTitle: 'Aún no hay artículos publicados', emptyMessage: 'Los nuevos textos aparecerán aquí cuando se publiquen.', retry: 'Intentar de nuevo', previous: 'Anterior', next: 'Siguiente', pagination: 'Paginación del archivo', uncategorized: 'Sin categoría', loadError: 'No se pudieron cargar los artículos. Comprueba la API e inténtalo de nuevo.', filteredError: 'No se pudieron cargar los artículos de {{name}}. Inténtalo de nuevo.', categoryDescription: 'Artículos de la categoría {{name}}.', tagDescription: 'Artículos con la etiqueta {{name}}.' },
  article: { notFound: 'Artículo no encontrado', unavailable: 'Este artículo no está disponible', notFoundMessage: 'Puede haberse movido, vuelto a borrador o no haber existido.', unavailableMessage: 'No se pudo cargar el artículo. Comprueba la API e inténtalo de nuevo.', tags: 'Etiquetas', noTags: 'Sin etiquetas', noContent: 'Aún no hay contenido.', allArticles: 'Todos los artículos', moreIn: 'Más en {{name}}', loading: 'Cargando artículo', return: 'Volver a todos los artículos', imageAlt: 'Imagen de cabecera de {{title}}' },
  login: { trigger: 'Admin', eyebrow: 'Restringido / 01', title: 'Acceso de administrador', close: 'Cerrar inicio de sesión', description: 'Introduce tus credenciales privadas para abrir el espacio de publicación.', username: 'Usuario', password: 'Contraseña', continue: 'Continuar', checking: 'Comprobando…', missing: 'Introduce el usuario y la contraseña.', incorrect: 'El usuario o la contraseña son incorrectos.', unavailable: 'El acceso de administrador no está disponible. Inténtalo de nuevo.', popup: 'Inicio de sesión correcto. Permite las ventanas emergentes para abrir el panel de administración.' },
  footer: { browse: 'Explorar el archivo', top: 'Volver arriba' },
  status: { notFoundMeta: 'Página no encontrada', errorMeta: 'Algo salió mal', notFoundDescription: 'No se encontró la página solicitada.', wrongTurn: 'Giro equivocado / Página vacía', interrupted: 'Sistema / Interrumpido', nowhere: 'Este camino no lleva a ninguna parte.', slipped: 'Esta página desapareció.', lostThread: 'La página perdió el hilo.', missingMessage: 'La página puede haberse movido, vuelto a borrador o no haber existido.', changedMessage: 'La dirección puede haber cambiado o la página ya no existe.', errorMessage: 'Un error inesperado interrumpió esta vista. Tu contenido no ha cambiado.', home: 'Volver al inicio', browse: 'Explorar artículos', retry: 'Intentar de nuevo' },
  meta: { defaultTitle: 'Notas y experimentos', defaultDescription: 'Archivo personal de software, escritura, viajes y experimentos digitales.' },
}
