export const hi = {
  language: { label: 'भाषा', english: 'अंग्रेज़ी', turkish: 'तुर्की', german: 'जर्मन', chinese: 'चीनी', spanish: 'स्पेनिश', hindi: 'हिन्दी' },
  navigation: { explore: 'खोजें', title: 'वेबसाइट खोजें', close: 'नेविगेशन बंद करें', home: 'होम', recent: 'नई रचनाएँ', personal: 'व्यक्तिगत टिप्पणी', allArticles: 'सभी लेख', categories: 'श्रेणियाँ', categoriesEmpty: 'श्रेणियाँ यहाँ दिखाई देंगी', unavailable: 'श्रेणियाँ उपलब्ध नहीं हैं', primary: 'मुख्य नेविगेशन', mobile: 'मोबाइल नेविगेशन', open: 'नेविगेशन खोलें', index: 'नेविगेशन' },
  home: { scroll: 'प्रवेश के लिए स्क्रॉल करें', local: 'स्थानीय', recent: 'नई रचनाएँ', viewAll: 'सभी देखें', personal: 'व्यक्तिगत टिप्पणी', currently: 'वर्तमान में', interested: 'रुचियाँ', archive: 'संग्रह खोजें', latestLoading: 'नए लेख लोड हो रहे हैं', offlineTitle: 'संग्रह ऑफ़लाइन है', offlineMessage: 'प्रकाशित लेख लोड करने के लिए API शुरू करें।', emptyTitle: 'अभी कोई प्रकाशित लेख नहीं', emptyMessage: 'प्रकाशित लेख यहाँ दिखाई देंगे।', status: 'संग्रह की स्थिति' },
  archive: { title: 'सभी लेख', description: 'सॉफ़्टवेयर, सिस्टम, इंटरफ़ेस और जारी प्रयोगों पर लेखन।', notes: 'लेख', loading: 'लेख लोड हो रहे हैं', label: 'लेख संग्रह', status: 'संग्रह की स्थिति', offlineTitle: 'संग्रह ऑफ़लाइन है', emptyTitle: 'अभी कोई प्रकाशित लेख नहीं', emptyMessage: 'प्रकाशित होने पर नई रचनाएँ यहाँ दिखाई देंगी।', retry: 'फिर प्रयास करें', previous: 'पिछला', next: 'अगला', pagination: 'संग्रह पृष्ठ', uncategorized: 'श्रेणी रहित', loadError: 'लेख लोड नहीं हो सके। API जाँचकर फिर प्रयास करें।', filteredError: '{{name}} के लेख लोड नहीं हो सके। फिर प्रयास करें।', categoryDescription: '{{name}} श्रेणी के लेख।', tagDescription: '{{name}} टैग वाले लेख।' },
  article: { notFound: 'लेख नहीं मिला', unavailable: 'यह लेख उपलब्ध नहीं है', notFoundMessage: 'यह स्थानांतरित, ड्राफ़्ट में वापस या कभी मौजूद न रहा हो सकता है।', unavailableMessage: 'लेख लोड नहीं हो सका। API जाँचकर फिर प्रयास करें।', tags: 'टैग', noTags: 'कोई टैग नहीं', noContent: 'अभी कोई सामग्री नहीं।', allArticles: 'सभी लेख', moreIn: '{{name}} में और पढ़ें', loading: 'लेख लोड हो रहा है', return: 'सभी लेखों पर लौटें', imageAlt: '{{title}} की शीर्ष छवि' },
  login: { trigger: 'एडमिन', eyebrow: 'प्रतिबंधित / 01', title: 'एडमिन प्रवेश', close: 'लॉगिन संवाद बंद करें', description: 'प्रकाशन कार्यक्षेत्र खोलने के लिए निजी क्रेडेंशियल दर्ज करें।', username: 'उपयोगकर्ता नाम', password: 'पासवर्ड', continue: 'जारी रखें', checking: 'जाँच हो रही है…', missing: 'उपयोगकर्ता नाम और पासवर्ड दोनों दर्ज करें।', incorrect: 'उपयोगकर्ता नाम या पासवर्ड गलत है।', unavailable: 'एडमिन लॉगिन उपलब्ध नहीं है। फिर प्रयास करें।', popup: 'लॉगिन सफल। एडमिन कार्यक्षेत्र खोलने के लिए पॉप-अप की अनुमति दें।' },
  footer: { browse: 'संग्रह देखें', top: 'ऊपर जाएँ' },
  status: { notFoundMeta: 'पृष्ठ नहीं मिला', errorMeta: 'कुछ गलत हुआ', notFoundDescription: 'अनुरोधित पृष्ठ नहीं मिला।', wrongTurn: 'गलत मोड़ / खाली पृष्ठ', interrupted: 'सिस्टम / बाधित', nowhere: 'यह रास्ता कहीं नहीं जाता।', slipped: 'यह पृष्ठ गायब हो गया।', lostThread: 'पृष्ठ ने अपनी कड़ी खो दी।', missingMessage: 'पृष्ठ स्थानांतरित, ड्राफ़्ट में वापस या कभी मौजूद न रहा हो सकता है।', changedMessage: 'पता बदल गया हो सकता है या पृष्ठ अब मौजूद नहीं है।', errorMessage: 'एक अप्रत्याशित त्रुटि ने इस दृश्य को बाधित किया। आपकी सामग्री नहीं बदली गई।', home: 'होम पर लौटें', browse: 'लेख देखें', retry: 'फिर प्रयास करें' },
  meta: { defaultTitle: 'नोट्स और प्रयोग', defaultDescription: 'सॉफ़्टवेयर, लेखन, यात्रा और डिजिटल प्रयोगों का व्यक्तिगत संग्रह।' },
}
